---
- hosts: "{{ hosts }}"
  tasks:
  - name: creamos un directorio temporal para descargar el apache
    win_file:
      path: C:\Temp
      state: directory
  - name: descargo el apache
    win_get_url: 
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Temp
  - name: Intalo el apache
    win_package:
      path: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi
      state: present
  - name: Set ServerAdmin in configfile
    win_lineinfile:
      path: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\httpd.conf
      regex: '^ServerAdmin'
      line: "ServerAdmin renzo@windows.com"
  - name: creamos web de inicio
    win_copy:
      content: "Bienvenido!!!"
      dest: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\index.html
  - name: validar si el servicio Apache2.2 existe
    win_service:
      name: Apache2.2
    register: apache_service
  - name: contenido de la variable apache_service
    debug:
      msg: "apache_service: {{ apache_service }}"
  - name: creamos servicio apache
    win_shell: '"C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin\httpd.exe" -k install'
    args:
      executable: cmd
    when: not apache_service.exists
  - name: levantar el servicio
    win_service:
      name: Apache2.2
      state: started
  - name: abrimos el puerto 80
    win_firewall_rule:
      name: HTTP
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enable: yes
    