---
- hosts: "{{ hosts }}"
  #gather_facts: false
  tasks:
  - name: crear el directorio prueba
    win_file:
      path: C:\Temp\prueba
      state: directory
    when: ansible_ip_addresses[0] == "192.168.17.201" 
